/**
 * Canonical action strings written to `audit_logs.action`. Extend this as new
 * audited mutations land (ads, promotions, locations, …) so producers and the
 * audit viewer share one vocabulary.
 */
export enum AuditAction {
  UserCreated = 'user.created',
  UserRoleUpdated = 'user.role_updated',
  UserActivated = 'user.activated',
  UserDeactivated = 'user.deactivated',
  UserHotelAssigned = 'user.hotel_assigned',
  UserHotelUnassigned = 'user.hotel_unassigned',
  AdvertisementCreated = 'advertisement.created',
  AdvertisementUpdated = 'advertisement.updated',
  AdvertisementDeleted = 'advertisement.deleted',
  PromotionCreated = 'promotion.created',
  PromotionUpdated = 'promotion.updated',
  PromotionDeleted = 'promotion.deleted',
  LocationCreated = 'location.created',
  LocationUpdated = 'location.updated',
  LocationDeleted = 'location.deleted',
  HotelCreated = 'hotel.created',
  HotelUpdated = 'hotel.updated',
  HotelActivated = 'hotel.activated',
  HotelDeactivated = 'hotel.deactivated',
  HotelImageUploaded = 'hotel.image_uploaded',
  HotelImageDeleted = 'hotel.image_deleted',
  RoomTypeCreated = 'room_type.created',
  RoomTypeUpdated = 'room_type.updated',
  RoomTypeDeleted = 'room_type.deleted',
  RoomTypeImageUploaded = 'room_type.image_uploaded',
  RoomTypeImageDeleted = 'room_type.image_deleted',
  RoomCreated = 'room.created',
  RoomUpdated = 'room.updated',
  RoomDeleted = 'room.deleted',
  HotelBookingCreated = 'hotel_booking.created',
  HotelBookingUpdated = 'hotel_booking.updated',
  HotelBookingCancelled = 'hotel_booking.cancelled',
  HotelBookingRoomAssigned = 'hotel_booking.room_assigned',
  FerryRouteCreated = 'ferry_route.created',
  FerryRouteUpdated = 'ferry_route.updated',
  FerryRouteDeleted = 'ferry_route.deleted',
  FerryScheduleCreated = 'ferry_schedule.created',
  FerryScheduleUpdated = 'ferry_schedule.updated',
  FerryScheduleDeleted = 'ferry_schedule.deleted',
  FerryBookingCreated = 'ferry_booking.created',
  FerryBookingUpdated = 'ferry_booking.updated',
  FerryBookingDeleted = 'ferry_booking.deleted',
  ParkTicketTypeCreated = 'park_ticket_type.created',
  ParkTicketTypeUpdated = 'park_ticket_type.updated',
  ParkTicketTypeDeleted = 'park_ticket_type.deleted',
  EventCreated = 'event.created',
  EventUpdated = 'event.updated',
  EventDeleted = 'event.deleted',
  EventScheduleCreated = 'event_schedule.created',
  EventScheduleUpdated = 'event_schedule.updated',
  EventScheduleDeleted = 'event_schedule.deleted',
  ParkDayCapacityUpdated = 'park_day_capacity.updated',
  ParkDayCapacityCleared = 'park_day_capacity.cleared',
  // `sold` and `validated` are the audit trail for money and physical access.
  ParkTicketSold = 'park_ticket.sold',
  ParkTicketValidated = 'park_ticket.validated',
  ParkTicketCancelled = 'park_ticket.cancelled',
  EventBookingCreated = 'event_booking.created',
  EventBookingUpdated = 'event_booking.updated',
  EventBookingCancelled = 'event_booking.cancelled',
}
