/**
 * Canonical action strings written to `audit_logs.action`. Extend this as new
 * audited mutations land (ads, promotions, locations, …) so producers and the
 * audit viewer share one vocabulary.
 */
export enum AuditAction {
  UserCreated = 'user.created',
  UserRoleUpdated = 'user.role_updated',
  UserActivated = 'user.activated',
  UserDeactivated = 'user.deactivated',
  AdvertisementCreated = 'advertisement.created',
  AdvertisementUpdated = 'advertisement.updated',
  AdvertisementDeleted = 'advertisement.deleted',
  PromotionCreated = 'promotion.created',
  PromotionUpdated = 'promotion.updated',
  PromotionDeleted = 'promotion.deleted',
  LocationCreated = 'location.created',
  LocationUpdated = 'location.updated',
  LocationDeleted = 'location.deleted',
  RoomTypeCreated = 'room_type.created',
  RoomTypeUpdated = 'room_type.updated',
  RoomTypeDeleted = 'room_type.deleted',
  RoomCreated = 'room.created',
  RoomUpdated = 'room.updated',
  RoomDeleted = 'room.deleted',
  HotelBookingCreated = 'hotel_booking.created',
  HotelBookingUpdated = 'hotel_booking.updated',
  HotelBookingCancelled = 'hotel_booking.cancelled',
  HotelBookingRoomAssigned = 'hotel_booking.room_assigned',
  ParkTicketTypeCreated = 'park_ticket_type.created',
  ParkTicketTypeUpdated = 'park_ticket_type.updated',
  ParkTicketTypeDeleted = 'park_ticket_type.deleted',
  EventCreated = 'event.created',
  EventUpdated = 'event.updated',
  EventDeleted = 'event.deleted',
  EventScheduleCreated = 'event_schedule.created',
  EventScheduleUpdated = 'event_schedule.updated',
  EventScheduleDeleted = 'event_schedule.deleted',
  ParkDayCapacityUpdated = 'park_day_capacity.updated',
  ParkDayCapacityCleared = 'park_day_capacity.cleared',
}
