/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardParkIndexRouteImport } from './routes/dashboard/park/index'
import { Route as DashboardHotelIndexRouteImport } from './routes/dashboard/hotel/index'
import { Route as DashboardFerryIndexRouteImport } from './routes/dashboard/ferry/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardAdminUsersIndexRouteImport } from './routes/dashboard/admin/users/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardParkIndexRoute = DashboardParkIndexRouteImport.update({
  id: '/park/',
  path: '/park/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHotelIndexRoute = DashboardHotelIndexRouteImport.update({
  id: '/hotel/',
  path: '/hotel/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFerryIndexRoute = DashboardFerryIndexRouteImport.update({
  id: '/ferry/',
  path: '/ferry/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminUsersIndexRoute =
  DashboardAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/ferry/': typeof DashboardFerryIndexRoute
  '/dashboard/hotel/': typeof DashboardHotelIndexRoute
  '/dashboard/park/': typeof DashboardParkIndexRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/ferry': typeof DashboardFerryIndexRoute
  '/dashboard/hotel': typeof DashboardHotelIndexRoute
  '/dashboard/park': typeof DashboardParkIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/ferry/': typeof DashboardFerryIndexRoute
  '/dashboard/hotel/': typeof DashboardHotelIndexRoute
  '/dashboard/park/': typeof DashboardParkIndexRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/admin/'
    | '/dashboard/ferry/'
    | '/dashboard/hotel/'
    | '/dashboard/park/'
    | '/dashboard/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/ferry'
    | '/dashboard/hotel'
    | '/dashboard/park'
    | '/dashboard/admin/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/admin/'
    | '/dashboard/ferry/'
    | '/dashboard/hotel/'
    | '/dashboard/park/'
    | '/dashboard/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/park/': {
      id: '/dashboard/park/'
      path: '/park'
      fullPath: '/dashboard/park/'
      preLoaderRoute: typeof DashboardParkIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/hotel/': {
      id: '/dashboard/hotel/'
      path: '/hotel'
      fullPath: '/dashboard/hotel/'
      preLoaderRoute: typeof DashboardHotelIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ferry/': {
      id: '/dashboard/ferry/'
      path: '/ferry'
      fullPath: '/dashboard/ferry/'
      preLoaderRoute: typeof DashboardFerryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/users/': {
      id: '/dashboard/admin/users/'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users/'
      preLoaderRoute: typeof DashboardAdminUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardFerryIndexRoute: typeof DashboardFerryIndexRoute
  DashboardHotelIndexRoute: typeof DashboardHotelIndexRoute
  DashboardParkIndexRoute: typeof DashboardParkIndexRoute
  DashboardAdminUsersIndexRoute: typeof DashboardAdminUsersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardFerryIndexRoute: DashboardFerryIndexRoute,
  DashboardHotelIndexRoute: DashboardHotelIndexRoute,
  DashboardParkIndexRoute: DashboardParkIndexRoute,
  DashboardAdminUsersIndexRoute: DashboardAdminUsersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
